// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Models;

namespace Project.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20191210214130_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Project.Models.Association", b =>
                {
                    b.Property<int>("AssociationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProductId");

                    b.Property<int>("id");

                    b.Property<int?>("weddingId");

                    b.HasKey("AssociationId");

                    b.HasIndex("id");

                    b.HasIndex("weddingId");

                    b.ToTable("Association");
                });

            modelBuilder.Entity("Project.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project.Models.Wedding", b =>
                {
                    b.Property<int>("weddingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Day");

                    b.Property<string>("NameWedderOne")
                        .IsRequired();

                    b.Property<string>("NameWedderTwo")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("weddingId");

                    b.ToTable("Weddings");
                });

            modelBuilder.Entity("Project.Models.Association", b =>
                {
                    b.HasOne("Project.Models.User", "User")
                        .WithMany("Weddings")
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Project.Models.Wedding", "Wedding")
                        .WithMany("Users")
                        .HasForeignKey("weddingId");
                });
#pragma warning restore 612, 618
        }
    }
}
